// x86-64 mnemonic → full name + syntax for ExplainPanel

const FULL_NAMES: Record<string, string> = {
  MOV: 'MOVE',
  MOVSX: 'MOVE WITH SIGN-EXTEND',
  MOVZX: 'MOVE WITH ZERO-EXTEND',
  LEA: 'LOAD EFFECTIVE ADDRESS',
  PUSH: 'PUSH',
  POP: 'POP',
  ADD: 'ADD',
  SUB: 'SUBTRACT',
  IMUL: 'SIGNED MULTIPLY',
  IDIV: 'SIGNED DIVIDE',
  CDQ: 'CONVERT DOUBLEWORD TO QUADWORD',
  CQO: 'CONVERT QUADWORD TO OCTOWORD',
  AND: 'BITWISE AND',
  OR: 'BITWISE OR',
  XOR: 'EXCLUSIVE OR',
  NOT: 'BITWISE NOT',
  NEG: 'NEGATE',
  SHL: 'SHIFT LEFT',
  SHR: 'SHIFT RIGHT (LOGICAL)',
  SAR: 'SHIFT RIGHT (ARITHMETIC)',
  CMP: 'COMPARE',
  TEST: 'TEST (BITWISE AND)',
  JMP: 'JUMP',
  JE: 'JUMP IF EQUAL',
  JZ: 'JUMP IF ZERO',
  JNE: 'JUMP IF NOT EQUAL',
  JNZ: 'JUMP IF NOT ZERO',
  JL: 'JUMP IF LESS',
  JNGE: 'JUMP IF NOT GREATER OR EQUAL',
  JLE: 'JUMP IF LESS OR EQUAL',
  JNG: 'JUMP IF NOT GREATER',
  JG: 'JUMP IF GREATER',
  JNLE: 'JUMP IF NOT LESS OR EQUAL',
  JGE: 'JUMP IF GREATER OR EQUAL',
  JNL: 'JUMP IF NOT LESS',
  JB: 'JUMP IF BELOW',
  JC: 'JUMP IF CARRY',
  JNAE: 'JUMP IF NOT ABOVE OR EQUAL',
  JBE: 'JUMP IF BELOW OR EQUAL',
  JNA: 'JUMP IF NOT ABOVE',
  JA: 'JUMP IF ABOVE',
  JNBE: 'JUMP IF NOT BELOW OR EQUAL',
  JAE: 'JUMP IF ABOVE OR EQUAL',
  JNC: 'JUMP IF NOT CARRY',
  JNB: 'JUMP IF NOT BELOW',
  JS: 'JUMP IF SIGN',
  JNS: 'JUMP IF NOT SIGN',
  JO: 'JUMP IF OVERFLOW',
  JNO: 'JUMP IF NOT OVERFLOW',
  CALL: 'CALL PROCEDURE',
  RET: 'RETURN FROM PROCEDURE',
  LEAVE: 'LEAVE (HIGH-LEVEL PROCEDURE EXIT)',
  NOP: 'NO OPERATION',
  SETE: 'SET IF EQUAL',
  SETNE: 'SET IF NOT EQUAL',
  SETL: 'SET IF LESS',
  SETLE: 'SET IF LESS OR EQUAL',
  SETG: 'SET IF GREATER',
  SETGE: 'SET IF GREATER OR EQUAL',
  XCHG: 'EXCHANGE',
}

const SYNTAXES: Record<string, string> = {
  MOV: 'MOV Rd, Rs/imm/[mem]',
  MOVSX: 'MOVSX Rd, Rs/[mem]',
  MOVZX: 'MOVZX Rd, Rs/[mem]',
  LEA: 'LEA Rd, [mem]',
  PUSH: 'PUSH r/imm',
  POP: 'POP r',
  ADD: 'ADD Rd, Rs/imm',
  SUB: 'SUB Rd, Rs/imm',
  IMUL: 'IMUL Rd, Rs {, imm}',
  IDIV: 'IDIV Rs  ; rdx:rax / Rs',
  CDQ: 'CDQ  ; eax → edx:eax',
  CQO: 'CQO  ; rax → rdx:rax',
  AND: 'AND Rd, Rs/imm',
  OR: 'OR Rd, Rs/imm',
  XOR: 'XOR Rd, Rs/imm',
  NOT: 'NOT Rd',
  NEG: 'NEG Rd',
  SHL: 'SHL Rd, imm/CL',
  SHR: 'SHR Rd, imm/CL',
  SAR: 'SAR Rd, imm/CL',
  CMP: 'CMP Ra, Rb/imm',
  TEST: 'TEST Ra, Rb/imm',
  JMP: 'JMP label/r',
  JE: 'JE label  ; ZF=1',
  JNE: 'JNE label  ; ZF=0',
  JL: 'JL label  ; SF≠OF',
  JLE: 'JLE label  ; ZF=1 or SF≠OF',
  JG: 'JG label  ; ZF=0 and SF=OF',
  JGE: 'JGE label  ; SF=OF',
  JB: 'JB label  ; CF=1',
  JBE: 'JBE label  ; CF=1 or ZF=1',
  JA: 'JA label  ; CF=0 and ZF=0',
  JAE: 'JAE label  ; CF=0',
  CALL: 'CALL label/r',
  RET: 'RET',
  LEAVE: 'LEAVE',
  NOP: 'NOP',
  SETE: 'SETE r8',
  SETNE: 'SETNE r8',
  SETL: 'SETL r8',
  SETLE: 'SETLE r8',
  SETG: 'SETG r8',
  SETGE: 'SETGE r8',
}

export function getFullName(instr: string): string | undefined {
  const mnemonic = instr.trim().split(/\s/)[0]?.toUpperCase() ?? ''
  return FULL_NAMES[mnemonic]
}

export function getSyntax(instr: string): string | undefined {
  const mnemonic = instr.trim().split(/\s/)[0]?.toUpperCase() ?? ''
  return SYNTAXES[mnemonic]
}
